[package]
name = "rusthash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "csum_lib"
path = "src/lib/mod.rs"
doctest = false

# [[bin]]
# name = "csum"
# path = "src/main.rs"

[dependencies]
